source: ./site
destination: ./public
exclude: ['*.scss']
include: ['.htaccess', '.nojekyll']
title: Scampersand
email: hello@scampersand.com
url: https://scampersand.com
defaults:
  - scope:
      path: ""
    values:
      layout: default
      linky_tech: true