source: ./site
destination: ./public
exclude: ['*.scss']
include: ['.htaccess', '.nojekyll']
title: Scampersand
email: hello@scampersand.com
url: https://scampersand.com
links:
  aron: https://arongriffis.com
  amy: https://amygriffis.com
kramdown:
  input: Pantsdown
pants:
  options: [1, 'named_entities', 'prevent_breaks']
defaults:
  - scope:
      path: ""
    values:
      layout: default
      linky_tech: true